### ISSUE TITLE
Discord M1 is damaged and can't be opened

### ISSUE THREAD

**Issue by yigitkonur** [331leo/Discord-M1#1]
The latest release (1.2.0) you have just published can't be opened whether loading in eject disk or running through /Applications folder:

<img width="372" alt="CleanShot 2021-05-27 at 07 00 51@2x" src="https://user-images.githubusercontent.com/9989650/119764024-4fae9200-beb9-11eb-8f67-c38896f258bf.png">

Can you please double-check your release?

Many thanks for sharing this!

**Comment by fxrcha** [comment]
Type 

```bash
xattr -cr /Applications/Discord\ M1.app 
```

on your terminal, and that should do it

**Comment by 331leo** [comment]
Thank you for having interest on my Repository! 
I just have known That Apple don't allow me to publish any Application without Code Signing.

You have two choices to run this Application.

1. run `xattr -cr /Applications/Discord\ M1.app` to ignore code signing policy for my Applicaion
2. Clone this Repository and run `yarn build` to get DMG file locally 

Thank you for Opening issue!
